import React from "react";
import Head from "next/head";
import styles from "../styles/Layout.module.scss";
import { Navigation } from "./Navigation";
import { Dialog } from "./Dialog";

export const Layout = ({ title, children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/picture.ico" />
      </Head>
      <main className={styles.main}>
        <Navigation />
        {children}
      </main>
      <Dialog />
    </div>
  );
};
